spring:
  profiles:
    active: prod
  cloud:
    config:
      allow-override: true
      override-none: true
      override-system-properties: true
  rabbitmq:
    host: 47.96.173.142
    port: 5672
    username: guest
    password: guest
#  redis:
#    host: 192.168.10.100
#    port: 6379
#    password: 123456
#    timeout: 15000
#    pool:
#      max-idle: 50
#      min-idle: 0
#      max-active: 200
#      max-wait: 10000
#    sentinel:
#      master: mymaster
#      nodes: 192.168.10.100:26379,192.168.10.110:26379,192.168.10.120:26379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/gem?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query: select 'x'
      validation-query-timeout: 600
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 1000000
      filters:  stat,log4j,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: 
        session-stat-max-count: 
        principal-session-name: 
        principal-cookie-name: 
        profile-enable: 
      stat-view-servlet:
        url-pattern: /druid/*
        enabled: true
        loginUsername: admin
        loginPassword: admin
        resetEnable: true
        allow: 192.168.1.110,127.0.0.1
        deny: 192.168.16.111
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka
