spring:
  profiles:
    active: dev
  rabbitmq:
    host: 47.96.173.142
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.10.100
    port: 6379
    password: 123456
    timeout: 15000
    pool:
      max-idle: 50
      min-idle: 0
      max-active: 200
      max-wait: 10000
    sentinel:
      master: mymaster
      nodes: 192.168.10.100:26379,192.168.10.110:26379,192.168.10.120:26379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/gem?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka
